"""Creates a working .env for the local demo with freshly generated secrets.

    python scripts/make_demo_env.py                 # prompts for your Groq key
    GROQ_API_KEY=gsk_... python scripts/make_demo_env.py

Refuses to overwrite an existing .env. Never prints the secrets it generates.
"""
import getpass
import os
import pathlib
import secrets
import sys

ENV_PATH = pathlib.Path(".env")

if ENV_PATH.exists():
    sys.exit(".env already exists - not overwriting. Delete it first if you want a fresh one.")

groq_key = os.environ.get("GROQ_API_KEY") or getpass.getpass("Groq API key (input hidden): ").strip()
if not groq_key:
    sys.exit("A Groq API key is required for the Ask page (LLM answers).")

content = f"""# Generated by scripts/make_demo_env.py -- never commit this file.
APP_ENV=development

# --- API auth (paste API_AUTH_KEY into the frontend's Connection page) ---
API_AUTH_KEY={secrets.token_urlsafe(32)}
METRICS_AUTH_KEY={secrets.token_urlsafe(32)}

# --- Postgres (hex so it is safe inside DATABASE_URL) ---
POSTGRES_USER=docint
POSTGRES_PASSWORD={secrets.token_hex(16)}
POSTGRES_DB=document_intelligence

# --- Qdrant ---
QDRANT_API_KEY={secrets.token_urlsafe(32)}

# --- LLM (Groq, OpenAI-compatible) ---
LLM_URL=https://api.groq.com/openai/v1
LLM_ENDPOINT=/chat/completions
LLM_MODEL=openai/gpt-oss-120b
LLM_TIMEOUT=30.0
LLM_API_KEY={groq_key}

# --- Browser origins allowed to call the API directly (Vite dev server / other ports).
# Not needed for the Docker frontend on :3000, which uses the same-origin /api proxy.
CORS_ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000
"""

ENV_PATH.write_text(content)
os.chmod(ENV_PATH, 0o600)
print("Wrote .env (mode 600). API_AUTH_KEY is inside it - that is the key the frontend asks for.")